In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_excel("onepiecedle_update.xlsx")

In [3]:
df.head()

,Name,Image,Gender,Age,Devil Fruit,Last Bounty,Debut Arc,Haki,Affiliation,Debut Chapter ; Episode
0,Monkey D. Luffy,monkey_d_luffy.jpg,Male,19,Zoan,3B,Romance Dawn,All,Straw Hat Pirates,Chapter 1; Episode 1
1,Roronoa Zoro,roronoa_zoro.jpg,Male,21,NaN,1.1B,Romance Dawn,All,Straw Hat Pirates,Chapter 3; Episode 1
2,Vinsmoke Sanji,vinsmoke_sanji.jpg,Male,21,NaN,1B,Baratie,ArmObs,Straw Hat Pirates,Chapter 43; Episode 20
3,Nami,nami.jpg,Female,20,NaN,366M,Orange Town,NaN,Straw Hat Pirates,Chapter 8; Episode 1
4,Nico Robin,nico_robin.jpg,Female,30,Paramecia,930M,Whiskey Peak,NaN,Straw Hat Pirates,Chapter 114; Episode 67

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     267 non-null    object
 1   Image                    267 non-null    object
 2   Gender                   267 non-null    object
 3   Age                      267 non-null    object
 4   Devil Fruit              131 non-null    object
 5   Last Bounty              264 non-null    object
 6   Debut Arc                267 non-null    object
 7   Haki                     118 non-null    object
 8   Affiliation              249 non-null    object
 9   Debut Chapter ; Episode  267 non-null    object
dtypes: object(10)
memory usage: 21.0+ KB

In [5]:
df["Age"]

0      19
1      21
2      21
3      20
4      30
       ..
262     8
263     8
264     8
265    69
266    30
Name: Age, Length: 267, dtype: object

## Converting Age to numerical

In [6]:
df["Age"] = df["Age"].astype(str).str.replace("+", "", regex=False)
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

## Clean Debut part

In [7]:
df["Episode"] = df["Debut Chapter ; Episode"]
df.drop(["Debut Chapter ; Episode"],axis=1,inplace=True)

In [8]:
df["Episode"] = df["Episode"].apply(lambda x: x.split(";")[1] if isinstance(x, str) else x)

In [9]:
df["Episode"]

0          Episode 1
1          Episode 1
2         Episode 20
3          Episode 1
4         Episode 67
           ...
262     Episode 1087
263     Episode 1094
264     Episode 1092
265      Episode 932
266        Episode 0
Name: Episode, Length: 267, dtype: object

## Bounty

In [10]:
df["Last Bounty"] = df["Last Bounty"].fillna(0)


def convert_bounty(value):
    if isinstance(value, str):
        if value.endswith("M"):  
            return float(value.replace("M", "")) * 1_000_000
        elif value.endswith("B"):  
            return float(value.replace("B", "")) * 1_000_000_000
        elif value.isnumeric():  
            return int(value)
    return 0  


df["Last Bounty"] = df["Last Bounty"].apply(convert_bounty)


df["Last Bounty"] = df["Last Bounty"].astype("int64")

In [11]:
df.head(200)

,Name,Image,Gender,Age,Devil Fruit,Last Bounty,Debut Arc,Haki,Affiliation,Episode
0,Monkey D. Luffy,monkey_d_luffy.jpg,Male,19,Zoan,3000000000,Romance Dawn,All,Straw Hat Pirates,Episode 1
1,Roronoa Zoro,roronoa_zoro.jpg,Male,21,NaN,1100000000,Romance Dawn,All,Straw Hat Pirates,Episode 1
2,Vinsmoke Sanji,vinsmoke_sanji.jpg,Male,21,NaN,1000000000,Baratie,ArmObs,Straw Hat Pirates,Episode 20
3,Nami,nami.jpg,Female,20,NaN,366000000,Orange Town,NaN,Straw Hat Pirates,Episode 1
4,Nico Robin,nico_robin.jpg,Female,30,Paramecia,930000000,Whiskey Peak,NaN,Straw Hat Pirates,Episode 67
...,...,...,...,...,...,...,...,...,...,...
195,Charlotte Smoothie,charlotte_smoothie.jpg,Female,35,Paramecia,932000000,Whole Cake Island,ArmObs,Big Mom Pirates,Episode 812
196,Charlotte Cracker,charlotte_cracker.jpg,Male,45,Paramecia,860000000,Whole Cake Island,ArmObs,Big Mom Pirates,Episode 796
197,Charlotte Perospero,charlotte_perospero.jpg,Male,50,Paramecia,700000000,Whole Cake Island,ArmObs,Big Mom Pirates,Episode 795
198,Charlotte Daifuku,charlotte_daifuku.jpg,Male,48,Paramecia,300000000,Whole Cake Island,ArmObs,Big Mom Pirates,Episode 826
199,Charlotte Oven,charlotte_oven.jpg,Male,48,Paramecia,300000000,Whole Cake Island,ArmObs,Big Mom Pirates,Episode 827

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         267 non-null    object
 1   Image        267 non-null    object
 2   Gender       267 non-null    object
 3   Age          267 non-null    int64
 4   Devil Fruit  131 non-null    object
 5   Last Bounty  267 non-null    int64
 6   Debut Arc    267 non-null    object
 7   Haki         118 non-null    object
 8   Affiliation  249 non-null    object
 9   Episode      267 non-null    object
dtypes: int64(2), object(8)
memory usage: 21.0+ KB

## Debut Arc

In [13]:
df['Debut Arc'].unique()[0]

'Romance Dawn'

In [14]:
arc_list = []
for i in range(0,len(df['Debut Arc'].unique())):
    arc_list.append(df['Debut Arc'].unique()[i])

In [15]:
arc_list

['Romance Dawn',
 'Baratie',
 'Orange Town',
 'Whiskey Peak',
 'Impel Down',
 'Drum Island',
 'Syrup Village',
 'Thriller Bark',
 'Water 7',
 'Sabaody Archipelago',
 'Dressrosa',
 'Long Ring Long Land',
 'Enies Lobby',
 'Reverie',
 'Arlong Park',
 'Loguetown',
 'Alabasta',
 'Jaya',
 'Whole Cake Island',
 'Amazon Lily',
 'Little Garden',
 'Reverse Mountain',
 'Marineford',
 'Skypiea',
 'Post-War',
 'Fishman Island',
 'Zou',
 'Punk Hazard',
 'Return To Sabaody',
 'Wano',
 'Egghead']

In [16]:
for i in arc_list:
    match i:
         case "Romance Dawn":
             print("Romance Down Gang")

Romance Down Gang

In [17]:
arc_dict ={
    'Romance Dawn': 0,
    'Orange Town': 1,
    'Syrup Village': 2,
    'Baratie': 3,
    'Arlong Park': 4,
    'Loguetown': 5,
    'Reverse Mountain': 6,
    'Whiskey Peak': 7,
    'Little Garden': 8,
    'Drum Island': 9,
    'Alabasta': 10,
    'Jaya': 11,
    'Skypiea': 12,
    'Long Ring Long Land': 13,
    'Water 7': 14,
    'Enies Lobby': 15,
    'Thriller Bark': 16,
    'Sabaody Archipelago': 17,
    'Amazon Lily': 18,
    'Impel Down': 19,
    'Marineford': 20,
    'Post-War': 21,
    'Return To Sabaody': 22,
    'Fishman Island': 23,
    'Punk Hazard': 24,
    'Dressrosa': 25,
    'Zou': 26,
    'Whole Cake Island': 27,
    'Reverie': 28,
    'Wano': 29,
    'Egghead': 30
}

In [18]:
df["Arc Index"] = df["Debut Arc"]
df["Arc Index"] = df["Arc Index"].map(arc_dict)

## Devil Fruit

In [19]:
df.loc[df["Devil Fruit"].isna(), "Devil Fruit"] = 'X'

## Haki

In [21]:
df.loc[df["Haki"].isna(), "Haki"] = 'X'

In [22]:
df.head(166)

,Name,Image,Gender,Age,Devil Fruit,Last Bounty,Debut Arc,Haki,Affiliation,Episode,Arc Index
0,Monkey D. Luffy,monkey_d_luffy.jpg,Male,19,Zoan,3000000000,Romance Dawn,All,Straw Hat Pirates,Episode 1,0
1,Roronoa Zoro,roronoa_zoro.jpg,Male,21,X,1100000000,Romance Dawn,All,Straw Hat Pirates,Episode 1,0
2,Vinsmoke Sanji,vinsmoke_sanji.jpg,Male,21,X,1000000000,Baratie,ArmObs,Straw Hat Pirates,Episode 20,3
3,Nami,nami.jpg,Female,20,X,366000000,Orange Town,X,Straw Hat Pirates,Episode 1,1
4,Nico Robin,nico_robin.jpg,Female,30,Paramecia,930000000,Whiskey Peak,X,Straw Hat Pirates,Episode 67,7
...,...,...,...,...,...,...,...,...,...,...,...
161,Baby 5,baby_5.jpg,Female,24,Paramecia,0,Punk Hazard,X,Straw Hat Grand Fleet,Episode 608,24
162,Gladius,gladius.jpg,Male,33,Paramecia,31000000,Punk Hazard,X,Donquixote Pirates,Episode 608,24
163,Monet,monet.jpg,Female,30,Logia,0,Punk Hazard,X,Donquixote Pirates,Episode 581,24
164,Caesar Clown,caesar_clown.jpg,Male,55,Logia,300000000,Punk Hazard,X,Germa Kingdom,Episode 581,24
165,Caribou,caribou.jpg,Male,32,Logia,210000000,Return To Sabaody,X,Caribou Pirates,Episode 519,22

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         267 non-null    object
 1   Image        267 non-null    object
 2   Gender       267 non-null    object
 3   Age          267 non-null    int64
 4   Devil Fruit  267 non-null    object
 5   Last Bounty  267 non-null    int64
 6   Debut Arc    267 non-null    object
 7   Haki         267 non-null    object
 8   Affiliation  249 non-null    object
 9   Episode      267 non-null    object
 10  Arc Index    267 non-null    int64
dtypes: int64(3), object(8)
memory usage: 23.1+ KB

In [24]:
df["Arc Index"].isna()

0      False
1      False
2      False
3      False
4      False
       ...
262    False
263    False
264    False
265    False
266    False
Name: Arc Index, Length: 267, dtype: bool

In [25]:
i = 0
while (i < 267) :
    if str(df["Arc Index"][i]) == 'nan':
        print(i)
        
    i += 1

In [26]:
df["Arc Index"][46]
df["Arc Index"][73]
df["Arc Index"][74]
df["Arc Index"][75]

np.int64(7)

In [27]:
df["Arc Index"][46]

np.int64(27)

## Affiliation

In [28]:
df.loc[df["Affiliation"].isna(), "Affiliation"] = 'X'

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         267 non-null    object
 1   Image        267 non-null    object
 2   Gender       267 non-null    object
 3   Age          267 non-null    int64
 4   Devil Fruit  267 non-null    object
 5   Last Bounty  267 non-null    int64
 6   Debut Arc    267 non-null    object
 7   Haki         267 non-null    object
 8   Affiliation  267 non-null    object
 9   Episode      267 non-null    object
 10  Arc Index    267 non-null    int64
dtypes: int64(3), object(8)
memory usage: 23.1+ KB

In [40]:
for i in range(0,len(df["Name"])):
    print(f'{df["Name"][i]} || {type(df["Name"][i])} ')
    print(f'{df["Image"][i]} || {type(df["Image"][i])} ')
    print(f'{df["Gender"][i]} || {type(df["Gender"][i])} ')
    print(f'{df["Age"][i]} || {type(df["Age"][i])} ')

Monkey D. Luffy || <class 'str'>
monkey_d_luffy.jpg || <class 'str'>
Male || <class 'str'>
19 || <class 'numpy.int64'>
Roronoa Zoro || <class 'str'>
roronoa_zoro.jpg || <class 'str'>
Male || <class 'str'>
21 || <class 'numpy.int64'>
Vinsmoke Sanji || <class 'str'>
vinsmoke_sanji.jpg || <class 'str'>
Male || <class 'str'>
21 || <class 'numpy.int64'>
Nami || <class 'str'>
nami.jpg || <class 'str'>
Female || <class 'str'>
20 || <class 'numpy.int64'>
Nico Robin || <class 'str'>
nico_robin.jpg || <class 'str'>
Female || <class 'str'>
30 || <class 'numpy.int64'>
Jinbe || <class 'str'>
jinbe.jpg || <class 'str'>
Male || <class 'str'>
46 || <class 'numpy.int64'>
Tony Tony Chopper || <class 'str'>
chopper.jpg || <class 'str'>
Male || <class 'str'>
17 || <class 'numpy.int64'>
Usopp || <class 'str'>
usopp.jpg || <class 'str'>
Male || <class 'str'>
19 || <class 'numpy.int64'>
Brook || <class 'str'>
brook.jpg || <class 'str'>
Male || <class 'str'>
90 || <class 'numpy.int64'>
Franky || <class 'str'>
franky.jpg || <class 'str'>
Male || <class 'str'>
36 || <class 'numpy.int64'>
Shanks || <class 'str'>
shanks.jpg || <class 'str'>
Male || <class 'str'>
39 || <class 'numpy.int64'>
Benn Beckman || <class 'str'>
benn_beckman.jpg || <class 'str'>
Male || <class 'str'>
50 || <class 'numpy.int64'>
Lucky Roux || <class 'str'>
lucky_roux.jpg || <class 'str'>
Male || <class 'str'>
35 || <class 'numpy.int64'>
Yasopp || <class 'str'>
yasopp.jpg || <class 'str'>
Male || <class 'str'>
47 || <class 'numpy.int64'>
Trafalgar D. Water Law || <class 'str'>
trafalgar_law.jpg || <class 'str'>
Male || <class 'str'>
26 || <class 'numpy.int64'>
Bepo || <class 'str'>
bepo.jpg || <class 'str'>
Male || <class 'str'>
22 || <class 'numpy.int64'>
Eustass Kid || <class 'str'>
eustass_kid.jpg || <class 'str'>
Male || <class 'str'>
23 || <class 'numpy.int64'>
Killer || <class 'str'>
killer.jpg || <class 'str'>
Male || <class 'str'>
27 || <class 'numpy.int64'>
Urouge || <class 'str'>
urouge.jpg || <class 'str'>
Male || <class 'str'>
47 || <class 'numpy.int64'>
Basil Hawkins || <class 'str'>
basil_hawkins.jpg || <class 'str'>
Male || <class 'str'>
31 || <class 'numpy.int64'>
Capone Bege || <class 'str'>
capone_bege.jpg || <class 'str'>
Male || <class 'str'>
42 || <class 'numpy.int64'>
Jewelry Bonney || <class 'str'>
jewelry_bonney.jpg || <class 'str'>
Female || <class 'str'>
24 || <class 'numpy.int64'>
Scratchmen Apoo || <class 'str'>
scratchmen_apoo.jpg || <class 'str'>
Male || <class 'str'>
31 || <class 'numpy.int64'>
X Drake || <class 'str'>
x_drake.jpg || <class 'str'>
Male || <class 'str'>
33 || <class 'numpy.int64'>
Koby || <class 'str'>
koby.jpg || <class 'str'>
Male || <class 'str'>
18 || <class 'numpy.int64'>
Fujitora Issho || <class 'str'>
ishho.jpg || <class 'str'>
Male || <class 'str'>
54 || <class 'numpy.int64'>
Aokiji Kuzan || <class 'str'>
kuzan.jpg || <class 'str'>
Male || <class 'str'>
49 || <class 'numpy.int64'>
Kizaru Borsalino || <class 'str'>
kizaru.jpg || <class 'str'>
Male || <class 'str'>
58 || <class 'numpy.int64'>
Akainu Sakazuki || <class 'str'>
sakazuki.jpg || <class 'str'>
Male || <class 'str'>
55 || <class 'numpy.int64'>
Ryokugyu Aramaki (Greenbull) || <class 'str'>
aramaki.jpg || <class 'str'>
Male || <class 'str'>
41 || <class 'numpy.int64'>
Monkey D. Garp || <class 'str'>
monkey_d_garp.jpg || <class 'str'>
Male || <class 'str'>
78 || <class 'numpy.int64'>
Smoker || <class 'str'>
smoker.jpg || <class 'str'>
Male || <class 'str'>
36 || <class 'numpy.int64'>
Tashigi || <class 'str'>
tashigi.jpg || <class 'str'>
Female || <class 'str'>
23 || <class 'numpy.int64'>
Hina || <class 'str'>
hina.jpg || <class 'str'>
Female || <class 'str'>
34 || <class 'numpy.int64'>
Bell-mère || <class 'str'>
bellmere.jpg || <class 'str'>
Female || <class 'str'>
30 || <class 'numpy.int64'>
Jaguar D. Saul || <class 'str'>
jaguar_d_saul.jpg || <class 'str'>
Male || <class 'str'>
127 || <class 'numpy.int64'>
Morgan || <class 'str'>
morgan.jpg || <class 'str'>
Male || <class 'str'>
44 || <class 'numpy.int64'>
Sengoku || <class 'str'>
sengoku.jpg || <class 'str'>
Male || <class 'str'>
79 || <class 'numpy.int64'>
Helmeppo || <class 'str'>
helmeppo.jpg || <class 'str'>
Male || <class 'str'>
20 || <class 'numpy.int64'>
Donquixote Rosinante (Corazon) || <class 'str'>
corazon.jpg || <class 'str'>
Male || <class 'str'>
26 || <class 'numpy.int64'>
Rob Lucci || <class 'str'>
rob_lucci.jpg || <class 'str'>
Male || <class 'str'>
30 || <class 'numpy.int64'>
Kaku || <class 'str'>
kaku.jpg || <class 'str'>
Male || <class 'str'>
25 || <class 'numpy.int64'>
Kalifa || <class 'str'>
kalifa.jpg || <class 'str'>
Female || <class 'str'>
27 || <class 'numpy.int64'>
Spandam || <class 'str'>
spandam.jpg || <class 'str'>
Male || <class 'str'>
41 || <class 'numpy.int64'>
Blueno || <class 'str'>
blueno.jpg || <class 'str'>
Male || <class 'str'>
32 || <class 'numpy.int64'>
Jabra || <class 'str'>
jabra.jpg || <class 'str'>
Male || <class 'str'>
37 || <class 'numpy.int64'>
Stussy || <class 'str'>
stussy.jpg || <class 'str'>
Female || <class 'str'>
36 || <class 'numpy.int64'>
Arlong || <class 'str'>
arlong.jpg || <class 'str'>
Male || <class 'str'>
41 || <class 'numpy.int64'>
Fisher Tiger || <class 'str'>
fisher_tiger.jpg || <class 'str'>
Male || <class 'str'>
48 || <class 'numpy.int64'>
Hatchan (Hachi) || <class 'str'>
hachi.jpg || <class 'str'>
Male || <class 'str'>
38 || <class 'numpy.int64'>
Makino || <class 'str'>
makino.jpg || <class 'str'>
Female || <class 'str'>
31 || <class 'numpy.int64'>
Higuma || <class 'str'>
higuma.jpg || <class 'str'>
Male || <class 'str'>
46 || <class 'numpy.int64'>
Buggy || <class 'str'>
buggy.jpg || <class 'str'>
Male || <class 'str'>
39 || <class 'numpy.int64'>
Chouchou || <class 'str'>
chouchou.jpg || <class 'str'>
Male || <class 'str'>
14 || <class 'numpy.int64'>
Mohji || <class 'str'>
mohji.jpg || <class 'str'>
Male || <class 'str'>
29 || <class 'numpy.int64'>
Alvida || <class 'str'>
alvida.jpg || <class 'str'>
Female || <class 'str'>
27 || <class 'numpy.int64'>
Galdino (Mr.3) || <class 'str'>
galdino.jpg || <class 'str'>
Male || <class 'str'>
37 || <class 'numpy.int64'>
Cabaji || <class 'str'>
cabaji.jpg || <class 'str'>
Male || <class 'str'>
34 || <class 'numpy.int64'>
Dracule Mihawk || <class 'str'>
dracule_mihawk.jpg || <class 'str'>
Male || <class 'str'>
43 || <class 'numpy.int64'>
Crocodile || <class 'str'>
crocodile.jpg || <class 'str'>
Male || <class 'str'>
46 || <class 'numpy.int64'>
Fullbody || <class 'str'>
fullbody.jpg || <class 'str'>
Male || <class 'str'>
28 || <class 'numpy.int64'>
Kaya || <class 'str'>
kaya.jpg || <class 'str'>
Female || <class 'str'>
19 || <class 'numpy.int64'>
Jango || <class 'str'>
jango.jpg || <class 'str'>
Male || <class 'str'>
29 || <class 'numpy.int64'>
Kuro || <class 'str'>
kuro.jpg || <class 'str'>
Male || <class 'str'>
35 || <class 'numpy.int64'>
Zeff || <class 'str'>
zeff.jpg || <class 'str'>
Male || <class 'str'>
67 || <class 'numpy.int64'>
Don Krieg || <class 'str'>
don_krieg.jpg || <class 'str'>
Male || <class 'str'>
44 || <class 'numpy.int64'>
Gin || <class 'str'>
gin.jpg || <class 'str'>
Male || <class 'str'>
27 || <class 'numpy.int64'>
Gol D. Roger || <class 'str'>
gol_d_roger.jpg || <class 'str'>
Male || <class 'str'>
53 || <class 'numpy.int64'>
Silvers Rayleigh || <class 'str'>
silvers_rayleigh.jpg || <class 'str'>
Male || <class 'str'>
78 || <class 'numpy.int64'>
Scopper Gaban || <class 'str'>
scopper_gaban.jpg || <class 'str'>
Male || <class 'str'>
78 || <class 'numpy.int64'>
Crocus || <class 'str'>
crocus.jpg || <class 'str'>
Male || <class 'str'>
73 || <class 'numpy.int64'>
Laboon || <class 'str'>
laboon.jpg || <class 'str'>
Male || <class 'str'>
53 || <class 'numpy.int64'>
Nefertari D. Vivi || <class 'str'>
nefertari_d_vivi.jpg || <class 'str'>
Female || <class 'str'>
18 || <class 'numpy.int64'>
Igaram || <class 'str'>
igaram.jpg || <class 'str'>
Male || <class 'str'>
50 || <class 'numpy.int64'>
Mr.5 (Gem) || <class 'str'>
mr_5.jpg || <class 'str'>
Male || <class 'str'>
26 || <class 'numpy.int64'>
Miss Valentine (Mikita) || <class 'str'>
miss_valentine.jpg || <class 'str'>
Female || <class 'str'>
24 || <class 'numpy.int64'>
Brogy || <class 'str'>
brogy.jpg || <class 'str'>
Male || <class 'str'>
160 || <class 'numpy.int64'>
Dorry || <class 'str'>
dorry.jpg || <class 'str'>
Male || <class 'str'>
160 || <class 'numpy.int64'>
Hiriluk || <class 'str'>
hiriluk.jpg || <class 'str'>
Male || <class 'str'>
68 || <class 'numpy.int64'>
Dalton || <class 'str'>
dalton.jpg || <class 'str'>
Male || <class 'str'>
35 || <class 'numpy.int64'>
Wapol || <class 'str'>
wapol.jpg || <class 'str'>
Male || <class 'str'>
29 || <class 'numpy.int64'>
Kureha || <class 'str'>
kureha.jpg || <class 'str'>
Female || <class 'str'>
141 || <class 'numpy.int64'>
Gaimon || <class 'str'>
gaimon.jpg || <class 'str'>
Male || <class 'str'>
45 || <class 'numpy.int64'>
Bon Clay (Bentham) (Mr.2) || <class 'str'>
bon_clay.jpg || <class 'str'>
Male || <class 'str'>
32 || <class 'numpy.int64'>
Portgas D. Ace || <class 'str'>
portgas_d_ace.jpg || <class 'str'>
Male || <class 'str'>
20 || <class 'numpy.int64'>
Pell || <class 'str'>
pell.jpg || <class 'str'>
Male || <class 'str'>
35 || <class 'numpy.int64'>
Karoo || <class 'str'>
karoo.jpg || <class 'str'>
Male || <class 'str'>
16 || <class 'numpy.int64'>
Koza  || <class 'str'>
koza.jpg || <class 'str'>
Male || <class 'str'>
22 || <class 'numpy.int64'>
Foxy || <class 'str'>
foxy.jpg || <class 'str'>
Male || <class 'str'>
38 || <class 'numpy.int64'>
Marshall D. Teach || <class 'str'>
marshall_d_teach.jpg || <class 'str'>
Male || <class 'str'>
40 || <class 'numpy.int64'>
Stronger || <class 'str'>
stronger.jpg || <class 'str'>
Male || <class 'str'>
17 || <class 'numpy.int64'>
Doc Q || <class 'str'>
doc_q.jpg || <class 'str'>
Male || <class 'str'>
28 || <class 'numpy.int64'>
Van Augur || <class 'str'>
van_augur.jpg || <class 'str'>
Male || <class 'str'>
27 || <class 'numpy.int64'>
Laffite || <class 'str'>
laffite.jpg || <class 'str'>
Male || <class 'str'>
41 || <class 'numpy.int64'>
Jesus Burgess || <class 'str'>
jesus_burgess.jpg || <class 'str'>
Male || <class 'str'>
29 || <class 'numpy.int64'>
Shiryu || <class 'str'>
shiryu.jpg || <class 'str'>
Male || <class 'str'>
44 || <class 'numpy.int64'>
Catarina Devon || <class 'str'>
catarina_devon.jpg || <class 'str'>
Female || <class 'str'>
36 || <class 'numpy.int64'>
Sanjuan Wolf || <class 'str'>
sanjuan_wolf.jpg || <class 'str'>
Male || <class 'str'>
99 || <class 'numpy.int64'>
Vasco Shot || <class 'str'>
vasco_shot.jpg || <class 'str'>
Male || <class 'str'>
38 || <class 'numpy.int64'>
Avalo Pizarro || <class 'str'>
avalo_pizarro.jpg || <class 'str'>
Male || <class 'str'>
42 || <class 'numpy.int64'>
Bellamy || <class 'str'>
bellamy.jpg || <class 'str'>
Male || <class 'str'>
27 || <class 'numpy.int64'>
Sarquiss || <class 'str'>
sarquiss.jpg || <class 'str'>
Male || <class 'str'>
27 || <class 'numpy.int64'>
Mont Blanc Cricket || <class 'str'>
mont_blanc_cricket.jpg || <class 'str'>
Male || <class 'str'>
43 || <class 'numpy.int64'>
Mont Blanc Noland || <class 'str'>
mont_blanc_noland.jpg || <class 'str'>
Male || <class 'str'>
39 || <class 'numpy.int64'>
Kalgara || <class 'str'>
kalgara.jpg || <class 'str'>
Male || <class 'str'>
39 || <class 'numpy.int64'>
Conis || <class 'str'>
conis.jpg || <class 'str'>
Female || <class 'str'>
21 || <class 'numpy.int64'>
Gan Fall || <class 'str'>
gan_fall.jpg || <class 'str'>
Male || <class 'str'>
68 || <class 'numpy.int64'>
Wyper || <class 'str'>
wyper.jpg || <class 'str'>
Male || <class 'str'>
24 || <class 'numpy.int64'>
Aisa || <class 'str'>
aisa.jpg || <class 'str'>
Female || <class 'str'>
11 || <class 'numpy.int64'>
Enel || <class 'str'>
enel.jpg || <class 'str'>
Male || <class 'str'>
39 || <class 'numpy.int64'>
Iceburg || <class 'str'>
iceburg.jpg || <class 'str'>
Male || <class 'str'>
40 || <class 'numpy.int64'>
Paulie || <class 'str'>
paulie.jpg || <class 'str'>
Male || <class 'str'>
26 || <class 'numpy.int64'>
Chimney || <class 'str'>
chimney.jpg || <class 'str'>
Female || <class 'str'>
10 || <class 'numpy.int64'>
Kokoro || <class 'str'>
kokoro.jpg || <class 'str'>
Female || <class 'str'>
72 || <class 'numpy.int64'>
Yokozuna || <class 'str'>
yokozuna.jpg || <class 'str'>
Male || <class 'str'>
30 || <class 'numpy.int64'>
Tom || <class 'str'>
tom.jpg || <class 'str'>
Male || <class 'str'>
67 || <class 'numpy.int64'>
Clover || <class 'str'>
clover.jpg || <class 'str'>
Male || <class 'str'>
85 || <class 'numpy.int64'>
Nico Olvia || <class 'str'>
nico_olvia.jpg || <class 'str'>
Female || <class 'str'>
33 || <class 'numpy.int64'>
Sabo || <class 'str'>
sabo.jpg || <class 'str'>
Male || <class 'str'>
22 || <class 'numpy.int64'>
Monkey D. Dragon || <class 'str'>
monkey_d_dragon.jpg || <class 'str'>
Male || <class 'str'>
55 || <class 'numpy.int64'>
Emporio Ivankov || <class 'str'>
emporio_ivankov.jpg || <class 'str'>
Male || <class 'str'>
53 || <class 'numpy.int64'>
Karasu || <class 'str'>
karasu.jpg || <class 'str'>
Male || <class 'str'>
47 || <class 'numpy.int64'>
Belo Betty || <class 'str'>
belo_betty.jpg || <class 'str'>
Female || <class 'str'>
34 || <class 'numpy.int64'>
Morley || <class 'str'>
morley.jpg || <class 'str'>
Male || <class 'str'>
160 || <class 'numpy.int64'>
Bartholomew Kuma || <class 'str'>
bartholomew_kuma.jpg || <class 'str'>
Male || <class 'str'>
47 || <class 'numpy.int64'>
Lindbergh || <class 'str'>
lindbergh.jpg || <class 'str'>
Male || <class 'str'>
37 || <class 'numpy.int64'>
Koala || <class 'str'>
koala.jpg || <class 'str'>
Female || <class 'str'>
23 || <class 'numpy.int64'>
Shakuyaku (Shakky) || <class 'str'>
shakky.jpg || <class 'str'>
Female || <class 'str'>
64 || <class 'numpy.int64'>
Camie || <class 'str'>
camie.jpg || <class 'str'>
Female || <class 'str'>
18 || <class 'numpy.int64'>
Sentomaru || <class 'str'>
sentomaru.jpg || <class 'str'>
Male || <class 'str'>
34 || <class 'numpy.int64'>
Charlotte Lola || <class 'str'>
charlotte_lola.jpg || <class 'str'>
Female || <class 'str'>
26 || <class 'numpy.int64'>
Gecko Moria || <class 'str'>
gecko_moria.jpg || <class 'str'>
Male || <class 'str'>
50 || <class 'numpy.int64'>
Hogback || <class 'str'>
hogback.jpg || <class 'str'>
Male || <class 'str'>
47 || <class 'numpy.int64'>
Absalom || <class 'str'>
absalom.jpg || <class 'str'>
Male || <class 'str'>
36 || <class 'numpy.int64'>
Perona || <class 'str'>
perona.jpg || <class 'str'>
Female || <class 'str'>
25 || <class 'numpy.int64'>
Shimotsuki Ryuma || <class 'str'>
shimotsuki_ryuma.jpg || <class 'str'>
Male || <class 'str'>
47 || <class 'numpy.int64'>
Duval || <class 'str'>
duval.jpg || <class 'str'>
Male || <class 'str'>
25 || <class 'numpy.int64'>
Boa Hancock || <class 'str'>
boa_hancock.jpg || <class 'str'>
Female || <class 'str'>
31 || <class 'numpy.int64'>
Boa Sandersonia || <class 'str'>
boa_sandersonia.jpg || <class 'str'>
Female || <class 'str'>
30 || <class 'numpy.int64'>
Boa Marigold || <class 'str'>
boa_marigold.jpg || <class 'str'>
Female || <class 'str'>
28 || <class 'numpy.int64'>
Marguerite || <class 'str'>
marguerite.jpg || <class 'str'>
Female || <class 'str'>
18 || <class 'numpy.int64'>
Magellan || <class 'str'>
magellan.jpg || <class 'str'>
Male || <class 'str'>
47 || <class 'numpy.int64'>
Hannyabal || <class 'str'>
hannyabal.jpg || <class 'str'>
Male || <class 'str'>
35 || <class 'numpy.int64'>
Inazuma || <class 'str'>
inazuma.jpg || <class 'str'>
Male || <class 'str'>
29 || <class 'numpy.int64'>
Edward Newgate || <class 'str'>
edward_newgate.jpg || <class 'str'>
Male || <class 'str'>
72 || <class 'numpy.int64'>
Marco || <class 'str'>
marco.jpg || <class 'str'>
Male || <class 'str'>
45 || <class 'numpy.int64'>
Jozu || <class 'str'>
jozu.jpg || <class 'str'>
Male || <class 'str'>
42 || <class 'numpy.int64'>
Vista || <class 'str'>
vista.jpg || <class 'str'>
Male || <class 'str'>
47 || <class 'numpy.int64'>
Izou || <class 'str'>
izou.jpg || <class 'str'>
Male || <class 'str'>
45 || <class 'numpy.int64'>
Little Oars Jr. || <class 'str'>
little_oars_jr.jpg || <class 'str'>
Male || <class 'str'>
72 || <class 'numpy.int64'>
Squard || <class 'str'>
squard.jpg || <class 'str'>
Male || <class 'str'>
52 || <class 'numpy.int64'>
Edward Weevil || <class 'str'>
edward_weevil.jpg || <class 'str'>
Male || <class 'str'>
35 || <class 'numpy.int64'>
Curly Dadan || <class 'str'>
curly_dadan.jpg || <class 'str'>
Female || <class 'str'>
55 || <class 'numpy.int64'>
Donquixote Doflamingo || <class 'str'>
donquixote_doflamingo.jpg || <class 'str'>
Male || <class 'str'>
41 || <class 'numpy.int64'>
Trebol || <class 'str'>
trebol.jpg || <class 'str'>
Male || <class 'str'>
49 || <class 'numpy.int64'>
Diamante || <class 'str'>
diamante.jpg || <class 'str'>
Male || <class 'str'>
45 || <class 'numpy.int64'>
Pica || <class 'str'>
pica.jpg || <class 'str'>
Male || <class 'str'>
40 || <class 'numpy.int64'>
Vergo || <class 'str'>
vergo.jpg || <class 'str'>
Male || <class 'str'>
41 || <class 'numpy.int64'>
Sugar || <class 'str'>
sugar.jpg || <class 'str'>
Female || <class 'str'>
22 || <class 'numpy.int64'>
Viola || <class 'str'>
viola.jpg || <class 'str'>
Female || <class 'str'>
29 || <class 'numpy.int64'>
Senor Pink || <class 'str'>
senor_pink.jpg || <class 'str'>
Male || <class 'str'>
46 || <class 'numpy.int64'>
Baby 5 || <class 'str'>
baby_5.jpg || <class 'str'>
Female || <class 'str'>
24 || <class 'numpy.int64'>
Gladius || <class 'str'>
gladius.jpg || <class 'str'>
Male || <class 'str'>
33 || <class 'numpy.int64'>
Monet || <class 'str'>
monet.jpg || <class 'str'>
Female || <class 'str'>
30 || <class 'numpy.int64'>
Caesar Clown || <class 'str'>
caesar_clown.jpg || <class 'str'>
Male || <class 'str'>
55 || <class 'numpy.int64'>
Caribou || <class 'str'>
caribou.jpg || <class 'str'>
Male || <class 'str'>
32 || <class 'numpy.int64'>
Neptune || <class 'str'>
neptune.jpg || <class 'str'>
Male || <class 'str'>
70 || <class 'numpy.int64'>
Otohime || <class 'str'>
otohime.jpg || <class 'str'>
Female || <class 'str'>
36 || <class 'numpy.int64'>
Shirahoshi || <class 'str'>
shirahoshi.jpg || <class 'str'>
Female || <class 'str'>
16 || <class 'numpy.int64'>
Vander Decken || <class 'str'>
vander_decken.jpg || <class 'str'>
Male || <class 'str'>
35 || <class 'numpy.int64'>
Hody Jones || <class 'str'>
hody_jones.jpg || <class 'str'>
Male || <class 'str'>
30 || <class 'numpy.int64'>
Carrot || <class 'str'>
carrot.jpg || <class 'str'>
Female || <class 'str'>
15 || <class 'numpy.int64'>
Wanda || <class 'str'>
wanda.jpg || <class 'str'>
Female || <class 'str'>
28 || <class 'numpy.int64'>
Inuarashi || <class 'str'>
inuarashi.jpg || <class 'str'>
Male || <class 'str'>
40 || <class 'numpy.int64'>
Nekomamushi || <class 'str'>
nekomamushi.jpg || <class 'str'>
Male || <class 'str'>
40 || <class 'numpy.int64'>
Pedro || <class 'str'>
pedro.jpg || <class 'str'>
Male || <class 'str'>
32 || <class 'numpy.int64'>
Kaido || <class 'str'>
kaido.jpg || <class 'str'>
Male || <class 'str'>
59 || <class 'numpy.int64'>
King (Alber) || <class 'str'>
king.jpg || <class 'str'>
Male || <class 'str'>
47 || <class 'numpy.int64'>
Queen || <class 'str'>
queen.jpg || <class 'str'>
Male || <class 'str'>
56 || <class 'numpy.int64'>
Jack || <class 'str'>
jack.jpg || <class 'str'>
Male || <class 'str'>
28 || <class 'numpy.int64'>
Page One || <class 'str'>
page_one.jpg || <class 'str'>
Male || <class 'str'>
20 || <class 'numpy.int64'>
Ulti || <class 'str'>
ulti.jpg || <class 'str'>
Female || <class 'str'>
22 || <class 'numpy.int64'>
Who's-Who || <class 'str'>
whos_who.jpg || <class 'str'>
Male || <class 'str'>
38 || <class 'numpy.int64'>
Black Maria || <class 'str'>
black_maria.jpg || <class 'str'>
Female || <class 'str'>
29 || <class 'numpy.int64'>
Sasaki || <class 'str'>
sasaki.jpg || <class 'str'>
Male || <class 'str'>
34 || <class 'numpy.int64'>
Kurozumi Tama (O-Tama) || <class 'str'>
kurozumi_tama.jpg || <class 'str'>
Female || <class 'str'>

In [30]:
excel_path = "one_piece_characters.xlsx"
df.to_excel(excel_path, index=False)